{\rtf1\ansi\ansicpg936\cocoartf2636
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;\f1\fnil\fcharset134 PingFangSC-Regular;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs14 \cf0 Log:\
  Level: debug # Log level: none, error, warning, info, debug \
  AccessPath: # ./access.Log\
  ErrorPath: # ./error.log\
DnsConfigPath: # ./dns.json Path to dns config \
Nodes:\
  -\
    PanelType: "V2board" # Panel type: SSpanel, V2board\
    ApiConfig:\
      ApiHost: \'93https://jay-cloud.com # 
\f1 \'d0\'de\'b8\'c4\'d5\'e2\'c0\'ef
\f0 \
      ApiKey: \'93jaycloudisthebest # 
\f1 \'d0\'de\'b8\'c4\'d5\'e2\'c0\'ef
\f0 \
      NodeID: 1\
      NodeType: V2ray # Node type: V2ray, Shadowsocks, Trojan\
      Timeout: 30 # Timeout for the api request\
      EnableVless: false # Enable Vless for V2ray Type, Remote configuration first\
      EnableXTLS: false # Enable XTLS for V2ray and Trojan, emote configuration first\
    ControllerConfig:\
      ListenIP: 0.0.0.0 # IP address you want to listen\
      UpdatePeriodic: 60 # Time to update the nodeinfo, how many sec.\
      EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well\
      CertConfig:\
        CertMode: dns # Option about how to get certificate: none, file, http, dns. Choose "none" will forcedly disable the tls config.\
        CertDomain: "node1.test.com" # Domain to cert\
        CertFile: ./cert/node1.test.com.cert # Provided if the CertMode is file\
        KeyFile: ./cert/node1.test.com.key\
        Provider: alidns # DNS cert provider, Get the full support list here: https://go-acme.github.io/lego/dns/\
        Email: test@me.com\
        DNSEnv: # DNS ENV option used by DNS provider\
          ALICLOUD_ACCESS_KEY: aaa\
          ALICLOUD_SECRET_KEY: bbb\
}